name: 'Morpheus'
description: 'Order a Morpheus catalog item'
inputs:
  name:
    description: 'The catalog item name'
    required: true
  parameters:
    description: 'Catalog item input parameters in JSON format'
    required: false
  verify_ssl:
    description: "Whether to verify the Morpheus server SSL certificate"
    required: false
    default: true
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
