name: 'Morpheus'
description: 'Provision Morpheus'
inputs:
  name:  # id of input
    description: 'The catalog item name'
    required: true
  parameters:
    description: 'Catalog item input parameters in JSON format'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
