on: [push]

jobs:
  morpheus_action_test_job:
    runs-on: ubuntu-latest
    name: Morpheus Github Action Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Call Morpheus
        env:
          MORPHEUS_API_URL: ${{ secrets.MORPHEUS_API_URL }}
          MORPHEUS_API_TOKEN: ${{ secrets.MORPHEUS_API_TOKEN }}
        uses: ./ # Uses an action in the root directory
        id: instanceProvision
        with:
          name: 'MongoDB'
          parameters: 
            - name: environment
              value: 1
            - name: databaseplan
              value: 147
            - name: mongodb_version
              value: 4.4
          timeout: 2
      - name: Get the output time
        run: echo "The time was ${{ steps.instanceProvision.outputs.time }}"
